spring:
  #oracle
  datasource:
    url: jdbc:oracle:thin:@192.168.29.134:1521:orcl
    username: plf
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false


mybatis:
#mybatis
  mapper-locations: classpath:static/plf/mapper/*/*.xml

server:
  port: 8000

logging:
  level:
     com.sunfong.plf : debug





