package com.sunfong.plf.mapper;

import com.sunfong.plf.dob.entity.PlfUser;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "plfUserMapper")
public interface PlfUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    int insert(PlfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    int insertSelective(PlfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    PlfUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    int updateByPrimaryKeySelective(PlfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLF_USER
     *
     * @mbg.generated 2018-10-29 17:36:57
     */
    int updateByPrimaryKey(PlfUser record);

    List selectByMap(Map params);
}